### ISSUE TITLE
Explore commit convention and towncrier for building changelogs in an automated way

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/actions#188]
💡 **Idea**
@AlejandroFernandezLuces suggested to follow [conventional commits] to unify commit messages. This is a great idea as it is an accepted standard. On top of that, this convention is used by changelog tools to create this document based on those commits.

- [x] **Implement a `check-conventional-commit` action**
  The goal is to make use of [amannn/action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request). By using this action together with [squash and merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) and the "commit message as pull-request title", we could ensure [conventional commits] without annoying developers when actually making commits. Everything happens in the pull-request.
  
- [x] **Implement a `check-changelog-fragments` action**
  The goal is to ensure that any pull-request (unless some condition) contains a changelog fragment requested by [towncrier](https://github.com/twisted/towncrier). [The Astropy project](https://www.astropy.org/) uses this tool in a very smart way together with  the [action-towncrier](https://github.com/pllim/actions-towncrier-changelog) action.
  
- [x] **Implement a `build-changelog` action**
  This action generates the changelog file following the configuration declared in the `pyproject.toml` file of every project. Ideally, we should enforce the [keep a changelog](https://keepachangelog.com/en/1.0.0/) convention.

[conventional commits]: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by AlejandroFernandezLuces** [comment]
I just did the first point today in a personal repo, to avoid testing in our public repositories. I also seized the opportunity to implement a branch naming convention checker, to avoid people from merging un labeled branches. @MaxJPRey is taking a look at it, I'll share the link and if you think it's appropriate we can open a PR with those actions here: https://github.com/AlejandroFernandezLuces/trame-slides/blob/main/.github/workflows/check-name.yml

**Comment by jorgepiloto** [comment]
Thanks for linking this, @AlejandroFernandezLuces. Let us explore [amannn/action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request) in favor of [aslafyz/conventional-pr-title](https://github.com/aslafy-z/conventional-pr-title-action), as the first one supports more options.

The one I am interested the most is the `ignore labels` one.

**Comment by klmcadams** [comment]
@jorgepiloto yep that sounds good!
