### ISSUE TITLE
Option to update version by the user

### ISSUE THREAD

**Issue by addie293** [ansys/actions#264]
Allow the user to update instances of subcomponents to newer versions of these subcomponents.

![Image](https://user-images.githubusercontent.com/40389482/233425541-9dd12b26-ae54-45c1-9158-347d0303468b.png)

- [ ] The context menu of assemblies in the tree should be having an option to update subcomponents to newer versions.

- [ ] On clicking the option, a dialogue (List of subcomponents that can be updated in the image) appears that shows the list of subcomponents for which newer versions are available. The components are sorted in a topological sense. Each entry has a button "Update".

- [ ] Clicking on "Update" for the component to be updated, it gives rise to a secondary dialogue (title: Newer Versions for Component Clicked on in the image) that shows the list of newer versions available with action item buttons: 1) "Update to this Version", 2) "Load and Preview". The secondary dialog is very similar to the "Version History Dialog", i.e. it also shows a graph, and all other columns, but it does not show older versions. (The currently used version does not have the buttons.)

- [ ] Clicking on the update button, it loads this component (if needed) and updates all instances of this component by the newer version chosen and closes the secondary dialogue. The primary dialog is refreshed (as some updates might be obsolete by now).

- [ ] Clicking on the preview button loads this component if needed and shows a preview in the scene if all instances of this component would be updated to this particular version. (The preview might be implemented in a later stage.)

Note: Changes might be "lost" (the modified subcomponents are still available, but the changes are no longer part of the active assembly). This would require some kind of merge, thus we ignore it for now.

Note: The recommended way for the user would be to update from top to bottom (as updates of higher levels might also affect lower levels).

**Comment by RobPasMue** [comment]
Hi @addie293 - I think this issue belongs https://github.com/ansys-internal/pyassembly.

Transfering the issue
