### ISSUE TITLE
Build wheelhouse action piping unintended output and breaking tests

### ISSUE THREAD

**Issue by raph-luc** [ansys/actions#269]
The following line is trying to pipe the entire output of `import` and `print` commands into the `GITHUB_ENV` variable:
https://github.com/ansys/actions/blob/a78b246d2b1319a6ed1bc66e1fdd0e635f66b660/build-wheelhouse/action.yml#L92

If on `import` the package outputs anything, it breaks the action as it all gets merged into the `GITHUB_ENV` var. I believe that is the reason for this failure:
https://github.com/ansys/pyfluent/actions/runs/5114660367/jobs/9195134134?pr=1651
Due to:
![image](https://github.com/ansys/actions/assets/132297401/3cefe1f2-7fe7-4a07-9fbd-e01df5ca297c)

I get `bash: $GITHUB_ENV: ambiguous redirect` if I try piping the entire output into a variable too, not sure how/why it works on the github runners (is it not bash?).

I believe we only want the output from the `print(__version__)` command piped into the `GITHUB_ENV` variable, in which case my suggestion would be to change [line 92](https://github.com/ansys/actions/blob/a78b246d2b1319a6ed1bc66e1fdd0e635f66b660/build-wheelhouse/action.yml#L92) to: 

-  `echo "library_version=$(python -c "from ${{ inputs.library-namespace }} import __version__; print(); print(__version__)" | tail -1)" >> $GITHUB_ENV` so that we only pipe the last line of the output, which should include only the output from the `print(version)` command we want. Also that extra `print();` to make sure output doesn't include any previous std output that did not end with a line break (shouldn't happen but probably better be safe).

An example commit where this was fixed and then the action `Build Documentation` which had previously failed for the same reason (and does not use `build-wheelhouse`) passed: https://github.com/ansys/pyfluent/pull/1651/commits/c65473dd550f322f9087cc8416f6f74677fb26d2

**Comment by RobPasMue** [comment]
My first question here @raph-luc is... where is the first print statement coming from? Do you print information in import? That's not really a good idea IMO, letting @jorgepiloto provide feedback here.

Also, why would I want a pyfluent log file when the only thing I am doing is importing the version?

For me the real problem is there, rather than adapting the version catcher statement... Of course we could adapt it but I still think that we should address the real issue here... why are you printing information on import and why are you creating a log file right after import... when maybe it isn't needed (for example, after retrieving the version I won't be doing anything else so... no need for logger).

**Comment by jorgepiloto** [comment]
Thanks for opening this, @raph-luc.

If a package or program writes more unnecessary information to standard output (stdout) when asked to print its version, it can be considered as a minor issue or inconvenience. While it doesn't directly affect the functionality or performance of the package, it may make the output less clean or cluttered.

For users and developers who need more information, explicit logging setup is the way to go.

**Comment by RobPasMue** [comment]
Hi @raph-luc I just remembered we still have this issue open. Following #276 we will be doing some further robustness improvements to the "import version" statement (in case no output is provided, then we will be throwing an error).

I know it doesn't address what you were asking for... but it got me thinking that we had a related issue and that's when I came back to this 😄 sorry for the delay!

As @jorgepiloto mentioned, if there's anything else being thrown to stdout during import of the library, then it might be considered as a minor issue on the library's side. I'd suggest to avoid doing that extra empty print. We should be only printing the version according to the statement.

Reading your last paragraph, I think you reached to our conclusion as well... Can we close this issue in that case? Let us know whenever you can! Or close it yourself if you think it is solved. Thanks @raph-luc and we appreciate your time!

**Comment by raph-luc** [comment]
Hi @RobPasMue, you are right, we worked around this on our end in PyFluent for the tests/github actions. 

I agree that printing to stdout on import should not be how packages work by default, but, as I said previously, a *lot* of things can happen on the initial import. I would not think it is ideal that this specific test is where this minor issue should be caught and breaking all subsequent tests, with unhelpful error messages like that.

My initial thought was that it is not safe to assume that packages will never print anything to stdout on import; and if they do print to stdout, then I believe we would not want this test to fail like it does here without providing any useful error messages as in my example above.

I think increasing robustness sounds good, perhaps throw a more helpful error if it notices multiple lines were output as well if you really want this test to error out due to this? I am going to take a look at that PR, thanks for the heads-up.

Feel free to close this issue or deal with this however you prefer, this was just a suggestion!
