### ISSUE TITLE
Add poetry support to tests-pytest action

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/actions#270]
### 📝 Description of the feature

The tests-pytest action currently does not fully support poetry-based projects. It will install dependencies from a pyproject.toml file, but it relies on a [tests] extra, instead of poetry dependency groups.

To support poetry-based projects, this action should do the following:

* Check if the project requires poetry as a build dependency
* If yes, install poetry
* Install the project with poetry. The action should take a list of groups to include and to exclude, and to pass these to the install step
* Run tests

**Comment by jorgepiloto** [comment]
Thanks for suggesting this, @Andy-Grigg.

**Comment by RobPasMue** [comment]
Closed by #299
