### ISSUE TITLE
Detect project name and namespace from pyproject.toml

### ISSUE THREAD

**Issue by da1910** [ansys/actions#280]
### 📝 Description of the feature

Currently we need to manually specify the project name and namespace in the workflow file in order to run `build-wheelhouse`. This is a bit of a shame, as we have the above information stored in `pyproject.toml`, it is not beyond the realm of possiblity to read this file...

### 💡 Steps for implementing the feature

Investigate whether we can read this information in a sensible way, perhaps with importlib-metadata, or by using tomli

### 🔗 Useful links and references

https://python-poetry.org/docs/pyproject/
https://flit.pypa.io/en/stable/pyproject_toml.html

**Comment by jorgepiloto** [comment]
After a quick:

```console
grep -r "library-namespace" .
```

I can see we are using this for extracting the version. Ideally, only the package name should be passed.

Let me adapt this logic.

**Comment by jorgepiloto** [comment]
This will require to add a deprecation warning in v4.0.
