### ISSUE TITLE
Multi-version redirection link is killing pages indexing

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/actions#284]
🐞 **Problem**
The main `index.html` created by the multi-version documentation looks as follows:

https://github.com/ansys/actions/blob/2070e78a8dc27a01d4f59bafacd4644d887d6fe9/doc-deploy-stable/action.yml#L356-L363

In previous code, the `<title>` tag encloses the following text: `Redirecting to...`. Because this text does not contain a proper title, Google is not properly indexing pages. Also, this index lacks a proper description and keywords. 

Solving this issue is urgent for any project using the multi-version documentation.

**Comment by RobPasMue** [comment]
Agreed - this should be handled ASAP :) let me know if you need any help
