### ISSUE TITLE
Add a deprecation warning in v4.0 because of the project name auto detection.

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/actions#290]
This will require to add a deprecation warning in v4.0.

_Originally posted by @jorgepiloto in https://github.com/ansys/actions/issues/280#issuecomment-1641442872_

**Comment by jorgepiloto** [comment]
Thanks for opening this issue, @MaxJPRey.

**Comment by jorgepiloto** [comment]
The issue with this is that I can no longer reference an input variable in the workflow that no longer exists. However, the default behavior of GitHub is to raise a warning during the CI about unnecessary variables.

**Comment by jorgepiloto** [comment]
Maybe I can add an admonition in the documentation of the action.
