### ISSUE TITLE
`build-wheelhouse` failing on Windows runners

### ISSUE THREAD

**Issue by raph-luc** [ansys/actions#309]
Seems to have started a few hours ago, see: 

https://github.com/ansys/pyfluent/actions/runs/5716250370/job/15487360994

https://github.com/ansys/pyfluent/actions/runs/5716166558/job/15487070117

The relevant error messages there probably are: 
`bc: command not found` 
`wget: command not found`

**Comment by RobPasMue** [comment]
wget issue was solved by #308 

bc still remains fixing https://github.com/ansys/pyfluent/actions/runs/5716250370/job/15487360994#step:2:699

**Comment by RobPasMue** [comment]
``choco install bc`` is not going to work. However... It looks like we are using it only for Python 3.7<= conditions... We have already deprecated the usage of Python 3.7 so it may not be that critical.

I will keep an eye on this and try to get it solved by tomorrow. We need to get it fixed. Thanks @raph-luc

**Comment by raph-luc** [comment]
True, if you don't support deprecated Python versions then I don't even think you need to check the Python version like that using `bc`,  only 3.8 and above are currently officially supported: https://devguide.python.org/versions/.

Thank you, Roberto!

**Comment by raph-luc** [comment]
After the `wget` update, it is now failing with:
```
Invalid licenses found:

pywin32 306 has Python license
```

**Comment by swilson-work** [comment]
@RobPasMue The line involving bc isn't working correctly even with bc installed. 3.10 and 3.11 compare as less than 3.8 numerically.

**Comment by RobPasMue** [comment]
I decided to remove bc as a whole. And implement it using ``awk`` which allows us to parse easily the major and minor numbers. Now, comparisons are performed consistently once #312 is merged and a new version is released.

I just need some minutes to do the latter. Thanks @raph-luc and @swilson-work for raising up the problems :)
