### ISSUE TITLE
License check support for `pywin32`

### ISSUE THREAD

**Issue by raph-luc** [ansys/actions#310]
https://github.com/ansys/pyfluent/actions/runs/5716250370/job/15490116459#step:2:2601
https://github.com/ansys/pyfluent/actions/runs/5716166558/job/15489329795#step:2:2603
`build-wheelhouse` currently failing due to:

```
Invalid licenses found:

pywin32 306 has Python license
```

Was perhaps `pypiwin32` a typo on the line below?

https://github.com/ansys/actions/blob/8ab872aa0a26d135eac38a7bf93fa4bf0bd92705/check-licenses/ignored-packages.txt#L3

Also, `pypiwin32` seems to be a deprecated package (see https://pypi.org/project/pypiwin32/) compared to `pywin32` (https://pypi.org/project/pywin32/)

Edit: `pywin32` uses a "Python Software Foundation License":

```
 Name                                   Version     License
 pywin32                                306         Python Software Foundation License
```

**Comment by RobPasMue** [comment]
Yep checking this first thing tomorrow morning. Thanks @raph-luc - also seen it in other repos
