### ISSUE TITLE
Explore the usage of sphinx-sitemap

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/actions#331]
💡 **Idea**
Explore the capabilities of https://sphinx-sitemap.readthedocs.io/en/latest/advanced-configuration.html and check whether it could replace our own action for this goal.

**Comment by MaxJPRey** [comment]
Interesting I saw this extension over the week-end and wanted to suggest some investigation.

**Comment by jorgepiloto** [comment]
Related with #375.

**Comment by jorgepiloto** [comment]
I am closing this since we are generating our sitemap with a custom shell script during actions. This avoids:

- Adding a new dependency in our libraries
- Ensuring the sitemap is updated everytime the CI/CD runs
