### ISSUE TITLE
Latest Vale version 2.29 is failing

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/actions#350]
🐞 **Problem**
Numerous issue have been raised with the latest patch release of Vale, v2.29.2. For some reason, the library is no longer ignoring inline code declared inside double back ticks.

💡 **Idea**
Let us allow users to indicate the Vale version by providing an optional input. This version will point to the latest working version for our libraries. This solves temporarily the issue until we have more information.

**Comment by RobPasMue** [comment]
Closed as solved
