### ISSUE TITLE
New license for check-license action

### ISSUE THREAD

**Issue by iazehaf** [ansys/actions#368]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

`ansys-templates` builds failed with the following error: `distlib 0.3.7 has Python license` ([logs](https://github.com/ansys/ansys-templates/actions/runs/7164743123/job/19514778525)). 

The Python license is not part of the accepted-licenses. 

### 📝 Steps to reproduce

Visit https://github.com/ansys/ansys-templates/actions/runs/7164743123/job/19514778525

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
It is a pipeline job failure.
```

**Comment by RobPasMue** [comment]
See #369

**Comment by iazehaf** [comment]
Thank you @RobPasMue.
