### ISSUE TITLE
Doc deploy action does not run on release/X.Y.Z branches

### ISSUE THREAD

**Issue by PProfizi** [ansys/actions#371]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Please allow for release/X.Y.Z branches to run a doc deploy. This makes these action unusable for PyDPF.
I know why the best practice is to maintain release/X.Y branches, but PyDPF is not managed that way for historical reasons and changing this is not doable right now, meaning these actions always fail and prevent me from having proper releases.
Either that or add an input to define a reference to checkout (the source commit/branch/tag), just like we can define the destination branch.

### 📝 Steps to reproduce

https://github.com/ansys/pydpf-core/actions/runs/7212438870/job/19650129551

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

None

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
None
```

**Comment by RobPasMue** [comment]
This is interesting. I can work on it this morning. We can accept some input to allow for patched versions to be online as well. Working on it.

**Comment by PProfizi** [comment]
Thanks @RobPasMue, I think a simple string parser [here](https://github.com/ansys/actions/blob/109b9909b974f3018d8ab81b84a84fa69816764e/doc-deploy-stable/action.yml#L162) getting `vX.Y` from `vX.Y.Z` may be enough.

**Comment by RobPasMue** [comment]
@PProfizi - please check the new ``v5`` release with the changes associated to the PR linked in this issue. It should work now. Let us know if you encounter any issues
