### ISSUE TITLE
Support mypy checks

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/actions#395]
### 📝 Description of the feature

Currently it's difficult to get mypy static type checking working with the code-style action. There are two ways of getting mypy checking to include dependencies with pre-commit: either add the dependencies to the pre-commit config, or use the 'system' language and install mypy as a development dependency of your project.

Specifying the dependencies in the pre-commit project isn't great, because they could get out of sync with your pyproject.toml. As a result, I've gone with the second option. However, the code-style action doesn't install the project dependencies, it only checks out the code.

This additional step should be added as an argument, so mypy can be used with the 'system' language.

**Comment by RobPasMue** [comment]
Sounds like a good idea! Do you have any example of what you are doing in your workflows currently to make it work?

I'd be happy to support this feature! Or any of my teammates for sure. @ansys/pyansys-core

**Comment by Andy-Grigg** [comment]
This commit https://github.com/ansys/grantami-jobqueue/pull/11/commits/37a9bab5c15fc159ba4da82e77c17740ba767268 shows the changes I've made to get it working. It's basically a copy-and-paste of the existing action, but with the extra step of creating a venv, installing the project into it, and then activating it before running pre-commit.

**Comment by RobPasMue** [comment]
These changes will go in with our next v5.1 - we are planning on doing that early next week. Thanks for the idea @Andy-Grigg!
