### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/actions#399]
🐞 **Problem**

This project follows a rolling release. That means we need to update the main and minor tags every time a new release is done. This translates into deleting these tags in the remote and re-tagging again. All this is manually and prone to error.

💡 **Idea**

Two ideas come to my mind:

- Use `tox.ini` and code the logic there for different platforms. Logic must be: read VERSION file -> delete necessary tags locally and remotely -> generate new tags -> upload new tags

- Create a `release.yml` workflow

**Comment by RobPasMue** [comment]
I prefer the release.yml mechanism :) only users with admin access will be allowed to do them

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules#about-tag-protection-rules

**Comment by SMoraisAnsys** [comment]
Great idea Jorge, I'm also inclined to use the second approach.

**Comment by jorgepiloto** [comment]
> I prefer the release.yml mechanism :) only users with admin access will be allowed to do them
> 
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules#about-tag-protection-rules

This is great! Thanks for your feedback @RobPasMue @SMoraisAnsys. Let's go with the `release.yml` then.

**Comment by dipinknair** [comment]
Adding to what @jorgepiloto mentioned regarding the pushing tags when doing a release might be prone to human. One case I have experienced is if you push the tag remotely without committing changes, it creates a draft release and more over complicates the release. Then I had to delete remote tag and re do all again etc.

**Comment by MaxJPRey** [comment]
+1 for the `release.yml.`
