### ISSUE TITLE
code-style action doesn't support Windows runners

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/actions#400]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

It is an exceptionally odd scenario that leads to requiring Windows, but I'll raise this ticket anyway. Feel free to disregard.

In the [openapi-common](https://github.com/ansys/openapi-common) package we depend on the gssapi python package. To install this package on Linux, the `krb5` package must be installed. It isn't installed on ubuntu-latest, and GitHub (understandably) doesn't give us root access, so we can't install this package.

Installing gssapi on Windows doesn't have this requirement.

For testing purposes, we use the python docker container which seemingly does give us root access, and so we can install the necessary package there. See https://github.com/ansys/openapi-common/blob/664a41240e4b7d713c0251faba79621f2c15f359/.github/workflows/ci_cd.yml#L79 if you're interested.

So to summarize, we can't use code-style for openapi common because:

* We want to do mypy checking, which requires installing the venv
* We can't use the ubuntu-latest runner, because it doesn't have krb5, so we can't install the package's dependencies
* We can't use the python docker image (or an ubuntu* or debian image) because it doesn't support installing Python using setup-python
* We can't use the windows-latest runner because this action doesn't support it

In my experience, the easiest way to get cross-platform support is to use the `pwsh` shell (on all github agents) and use the powershell version to activate the venv: `venv/*/Activate.ps1` does the trick.

\* This generates some really weird looking error messages. I can't tell for certain that it's even supported, so I'm just not going to bother exploring.

### 📝 Steps to reproduce

N/A - see above

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

N/A - CI only

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
N/A
```

**Comment by Andy-Grigg** [comment]
There are a few gotchas to poetry on Windows, the main one is that poetry needs to be installed outside the venv, otherwise any package that depends on a different version of a poetry dependency will fail to install

**Comment by RobPasMue** [comment]
Hi @Andy-Grigg - you are saying you can't do a ```sudo apt-get install krb5``` on the GH runners? And waht about ```sudo apt-get install krb5-user```?

**Comment by RobPasMue** [comment]
OS-independent support for actions - especially when commands are different ... common way to do so is to specify the kind of shell each step runs on. GitHub should transform commands accordingly AFAIK - but it might not be doing it.
