### ISSUE TITLE
Add a major changes site in the documentation

### ISSUE THREAD

**Issue by RobPasMue** [ansys/actions#409]
We should add a page in our hosted docs for the actions where we define the major changes between versions and the related modifications to be done.

**Comment by jorgepiloto** [comment]
Maybe we can start using Towncrier as an advance of #408.

**Comment by RobPasMue** [comment]
Hmm I doubt towncrier is the final solution. It won't be a pure changelog. I am also intending to add breaking changes guidelines on how to adapt to it. I will open a PR shortly.
