### ISSUE TITLE
Add target branch option for actions.

### ISSUE THREAD

**Issue by dipinknair** [ansys/actions#422]
Currently some of actions uses `checkout` for cloning repo. For example, code-style action uses
```
    - name: "Install Git and clone project"
      uses: actions/checkout@v4
 ```
 which takes the default `main` branch. Currently no option to specify for different branch where `checkout` action can use `ref:` to take input branch name. 
 
 We can possibly add one more input in actions which passes to checkout action.
 
 This will be helpful if a scheduled ci/cd action is running and want to use feature/develop branch

**Comment by jorgepiloto** [comment]
Hi @dipinknair, thanks for suggesting this.

Regarding the use case you present here, what about modifying the scheduled CI/CD action in the same branch where the feature is implemented?

**Comment by dipinknair** [comment]
> Hi @dipinknair, thanks for suggesting this.
> 
> Regarding the use case you present here, what about modifying the scheduled CI/CD action in the same branch where the feature is implemented?

But then the schedule action will not run in feature branch right ? CI/CD schedule action runs only on main branch. May be I am not understanding what you meant.
This is very low priority and might even not needed currently for us. I went with changing files with `sed` command to change files of `main` branch for scheduled action so that feature/develop branch is not needed.

**Comment by jorgepiloto** [comment]
From the checkout action:

> When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event. Otherwise, uses the default branch.

If you want to run a CI/CD on a branch because you have some changes there, just open a pull-request. If you want to avoid a PR, you can always modify the workflows in that branch to fit your needs, like using a cron job.

Let me now if this works for your situation.

**Comment by jorgepiloto** [comment]
After discussing privately, we can close this issue.
