### ISSUE TITLE
Rework accessing PR title in changelog action

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/actions#443]
Currently, the doc-changelog action retrieves the title of the PR using `${{ github.event.pull_request.title }}`.
When the title is edited, one may not retrieve the right title unless the workflow is configured to work on PR title edition, for example:
```
pull_request:
    types: [opened, reopened, synchronize, edited]
```
However, specifying such options will trigger the other jobs of the workflow when the PR title is updated.
This can be quite burdensome as merging a PR can preempted for 30+ minutes (or even more) because you have to rerun everything after figuring out that the title is not correct.

**Comment by RobPasMue** [comment]
This seems to me more like a repository issue... how would you propose to do it otherwise?

**Comment by SMoraisAnsys** [comment]
Closing since a modifications on the title creates a new commit (which should trigger the whole workflow).
