### ISSUE TITLE
feat: allow _logging action to work with windows

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/actions#449]
### 📝 Description of the feature

Currently one has to ensure that `bash` is in the `PATH` of a runner to use this action. Otherwise, the runner simply state that `bash` is not a known command. Since multiple of our self hosted runners don't have such set up, we could provide a way to use this action without requiring extra steps. This way, future actions dedicated to windows could use the _logging action without breaking changes.

**Comment by RobPasMue** [comment]
Agreed - let's make it OS agnostic

**Comment by jorgepiloto** [comment]
Merged in https://github.com/ansys/actions/pull/450. Closing this. Thanks @SMoraisAnsys.
