### ISSUE TITLE
Allow release-github action to use the changelog output

### ISSUE THREAD

**Issue by RobPasMue** [ansys/actions#460]
We should try to combine both actions: changelog build and release-github. That way when we release, we can include the changelog of the current version inside the release notes on GitHub. ``softprops/action-gh-release`` allows for it so it should be feasible

**Comment by MaxJPRey** [comment]
That's an excellent idea. I would encourage maintainers of PyAnsys packages to use the changelog action an implement changelog in their doc as much as possible.

That would bring a lot of consistency and provide valuable info for users.

**Comment by jorgepiloto** [comment]
If we could include these for v8 before its release, it would be great

**Comment by jorgepiloto** [comment]
Just moving this to v8.1.

**Comment by RobPasMue** [comment]
Better idea - this implementation might take some time (hours/days) - I wouldn't want to block v8 for it. We can do v8.1 once we have it =)

**Comment by RobPasMue** [comment]
@klmcadams - please plan on working on this shortly.
