### ISSUE TITLE
Extend doc-build action with asset upload

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/actions#466]
### 📝 Description of the feature

Some repos are using an extra step in the documentation build to add download assets to the HTML documentation.
See for example [assets page](https://geometry.docs.pyansys.com/version/stable/assets.html) where the assets are listed and a button has been added to download PDF files from HTML documentation.

### 💡 Steps for implementing the feature

Add extra steps to zip / copy / paste files to the expected directory.

**Comment by RobPasMue** [comment]
I would say that HTML in zip format and PDF file should be uploaded for now :)

**Comment by SMoraisAnsys** [comment]
I was wondering whether to add JSON files (if built) but felt that their main value was to be download as artifacts. Any thing I'm missing ?

**Comment by RobPasMue** [comment]
If somebody else asks for other files we can work on generalizing this. I believe this is already a good start nonetheless

**Comment by MaxJPRey** [comment]
> I was wondering whether to add JSON files (if built) but felt that their main value was to be download as artifacts. Any thing I'm missing ?

I think you listed all of them. No need to add the JSON. I had to used them at some point but it was for a specific extra work.
