### ISSUE TITLE
Exclude the changelog fragments from the vale check by default

### ISSUE THREAD

**Issue by da1910** [ansys/actions#477]
Changelog fragments are stored as .md files which means vale tries to check them. They frequently contain library names and other things that vale decides aren't correct.

Rather than having every library separately try to work out what regex to use to exclude the things they want as well as all the fragment files, can we add that exclusion here please? I know vale is a complete pain to use, but lets make it slightly less horrid for library developers!

**Comment by SMoraisAnsys** [comment]
@da1910 Thanks for bringing this problem ! I'm sure this will affect a lot of other repos.
