### ISSUE TITLE
Update doc-actions to work with Ansys developers' portal

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/actions#49]
💡 **Idea**
The [Ansys developers' portal](https://developer.ansys.com/) was recently launched. It includes some references to PyAnsys libraries documentation, see [PyAnsys documentation](https://developer.ansys.com/Documentation).

Previous documentation was generated after the discussion started in https://github.com/pyansys/pyaedt/issues/1726.

Notice we already support https://github.com/pyansys/actions/blob/6c6a5d952b7a2d78ae6dd9114b784f9baeea4249/doc-build/action.yml#L90-L96

Therefore, it is just a matter of adding any additional logic after previous lines of code get executed.

**Comment by jorgepiloto** [comment]
Assigning this to @MaxJPRey, as he is more familiar with the process to be carried out.

Once this is implemented, we can release v1.0 for our actions.

**Comment by MaxJPRey** [comment]
Works for me @jorgepiloto .

**Comment by RobPasMue** [comment]
I think this issue would imply just creating a new action that "deploys" documentation to the dev-portal... right?

**Comment by MaxJPRey** [comment]
Well actually, we also need to flatten the generated nested json files into a single directory.

**Comment by jorgepiloto** [comment]
Blocking this action till we get better feedback from the developer's portal.

**Comment by jorgepiloto** [comment]
It has been more than a year with this issue open. The current status is to have cards redirecting to the docs hosted in GitHub pages, see https://developer.ansys.com/docs/pyansys.

Thus, I am closing this issue.
