### ISSUE TITLE
Allow users to specify packages to ignore while running the license checker

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/actions#516]
### 📝 Description of the feature

Currently the license checker only accepts licenses from the accepted-licenses.txt file. However, there are other licenses that are compatible with our way of doing open source and that our projects might want to use. As an example, LPGL v3 seems to be one of them.

However, each of this compatible licenses might come with their own constraints. Thus, instead of extending the accepted licenses text file, I propose that we provide a new input to let developers ignore some packages. This should come with a warning to notify that every developer leveraging this input is responsible to ensure the compatibility with the associated license AND must follow the constraints of the associated license.

As an example, in the case of LGPL v3, we must:
- give prominent notice that the package is used in it and that the package and its use are covered by lgpl-3.0
- add a copy of the GNU GPL and LGPL v3 in the repo
- ...

### 💡 Steps for implementing the feature

Add ignore-packages input

**Comment by MaxJPRey** [comment]
+1.

**Comment by RobPasMue** [comment]
Let me work on this - should be quick

**Comment by SMoraisAnsys** [comment]
@RobPasMue Sure, go ahead ! Sry for the delay, I couldn't focus on this task...
