### ISSUE TITLE
Issues with new changelog action features

### ISSUE THREAD

**Issue by RobPasMue** [ansys/actions#535]
As ref: [ci: updating Ansys actions to v7 - changelog related by RobPasMue · Pull Request #1348 · ansys/pyansys-geometry (github.com)](https://github.com/ansys/pyansys-geometry/pull/1348)

- [ ] Whenever the config types are not defined, they get committed by the action. We shouldn't be committing that part IMO. We should only use the default config and throw it away once the fragment gets generated.
- [ ] If I have a local configuration BUT I am requesting to use the default config, we should inform the users what's going to happen.. (i.e. the default config gets ignored).
- [ ] We might have to clarify what the default config does --> web based changelog, We might want to expose a way to use default config for repo based changelog via an argument.
- [ ] The doc-deploy-changelog action has to be adapted as well to use the default config. Currently if you remove the config but you try to build the towncryer changelog, it will fail.

**Comment by klmcadams** [comment]
@RobPasMue should I close this issue?

**Comment by RobPasMue** [comment]
Yep, closing it. Thanks @klmcadams
