### ISSUE TITLE
Problem in determining the build backend in doc-build actions when no pyproject.toml file exist

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/actions#544]
At the moment there is no check on the existence of the `pyproject.toml` file in our doc build actions. However, this file is leveraged to decide which backend should be used in our CICD, see https://github.com/ansys/actions/blob/8643c5a882d18be06255fa8cc6e32bd9cc7e8cf1/_doc-build-linux/action.yml#L188 and https://github.com/ansys/actions/blob/8643c5a882d18be06255fa8cc6e32bd9cc7e8cf1/_doc-build-linux/action.yml#L198.

If this is a requirement then we should put it somewhere in the documentation. If that's not the case then we should fix the current action to add this check. Note that this would help projects which have no `pyproject.toml` file, e.g. projects mainly composed of examples. Currently, I'm not sure that they are able to use the `doc-build` action.

**Note**: speaking of projects without `pyproject.toml` file, we could use `pip` as default backend in those cases. What do you think ?

**Comment by SMoraisAnsys** [comment]
> Which project is still not using `pyproject.toml`?

I was mainly thinking about example repos, e.g. [pymapdl-examples](https://github.com/ansys/pymapdl-examples) or  [pymechanical-examples](https://github.com/ansys/pymechanical-examples).

I don't think we have other public repos without `pyproject.toml`

**Comment by RobPasMue** [comment]
Fine in that case =)

**Comment by MaxJPRey** [comment]
Agreed to use pip by default.
