### ISSUE TITLE
Rename `commit-style` to something related to pull request name

### ISSUE THREAD

**Issue by germa89** [ansys/actions#571]
Currently the action `commit-style` does not check the commit, but the pull request name.

https://github.com/ansys/actions/blob/release/7.0/commit-style/action.yml

Hence, I would propose to rename it something like:

``ansys/actions/pullrequest-name`` or similar... I actually dont care much, but the name is confusing.

**Comment by germa89** [comment]
Pinging @klmcadams @RobPasMue

**Comment by klmcadams** [comment]
I agree, maybe we could make it `ansys/actions/check-pr-name`?

**Comment by RobPasMue** [comment]
Completely agreed - could we do this with the v8 change @ansys/pyansys-core?

**Comment by SMoraisAnsys** [comment]
Agreed and voting for `check-pr-title` :)

**Comment by MaxJPRey** [comment]
+1 for `check-pr-title`.
