### ISSUE TITLE
Deprecate `MeiliSearch` and remove doc deploy index action

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/actions#574]
This issue proposes the removal of the doc deploy index action in favor of deprecating MeiliSearch.

**Comment by RobPasMue** [comment]
@Revathyvenugopal162 - we should notify of all these breaking changes in the migration guide. Could you handle this?

**Comment by RobPasMue** [comment]
https://github.com/ansys/actions/tree/main/doc/source/migrations

**Comment by Revathyvenugopal162** [comment]
> @Revathyvenugopal162 - we should notify of all these breaking changes in the migration guide. Could you handle this?

Sure , i can add. Thanks @RobPasMue

**Comment by RobPasMue** [comment]
Please ping the entire team before submitting the PR. We should make sure all of our breaking changes are reflected.
