### ISSUE TITLE
Enforce `doc-build` with a check of the success in building HTML files

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/actions#583]
I want to use the `doc-build` action with `pyaedt-examples`. Our workflow is such that running all examples takes ~3-4 hours. However, from time to time, we have errors appearing in an example as we make the API evolve in `pyaedt`. In such cases building the HTML files stops after an arbitrary amount of time, e.g. 2 hours. However, this doesn't stop the action and it then tries to run the examples to create the PDF files. This is a problem because they will fail in the same way as the previous step, e.g. after 2 hours.

Could we had a simple check after the build of HTML files to ensure it succeeded ?

I gave it a try in the past and here was the workaround for windows. If someone has a better approach, that would be great. Note that this should be taking into account the fact that one uses `nbsphinx_allow_errors = False` in the doc settings.

```
      # NOTE: Ugly HTML checking but redirecting errors with our docs either leads
      # to errors in powershell or workflows getting stuck in Github CICD.
      - name: Check HTML doc creation
        run : |
          if (Test-Path "doc\_build\html\index.html" ) {
            Write-Output "File index.html found, HTML build successful."
          } else {
            Write-Error "Sphinx build failed, check if there is no cell execution error."
            exit 1            
          }
```

**Comment by jorgepiloto** [comment]
Thanks for opening this, @SMoraisAnsys.

**Comment by RobPasMue** [comment]
We've got something similar working on PyAnsys Geometry:

https://github.com/ansys/pyansys-geometry/blob/40e9a0afafcd8c9b3831c80c37de1979a07ad74e/.github/workflows/ci_cd.yml#L298-L312

We are not only checking HTML build, but also PDF build
