### ISSUE TITLE
bug: changelog fragment creation broken whenever we have double quotes in the content

### ISSUE THREAD

**Issue by RobPasMue** [ansys/actions#639]
See https://github.com/ansys/pyansys-geometry/actions/runs/11801654551/job/32875549474?pr=1534#step:2:146

![Image](https://github.com/user-attachments/assets/2ad1fc85-96b2-4325-9296-660953809621)

If double quotes are used inside the title, the new modifications are no longer working.
We need to fix this @klmcadams - it was working previously AFAIK

**Comment by klmcadams** [comment]
Closed by #642
