### ISSUE TITLE
Ignore labeler in case an outside collaborator is submitting a request

### ISSUE THREAD

**Issue by RobPasMue** [ansys/actions#645]
Following #643 we should consider ignoring write operations on GitHub in case a user does not have write access to a repo. This happens whenever a user submits a PR coming from a forked repo, for example. We could simply skip it under those circumstances. This should be backported to all repos since we all (or most of us) suffer from it. We should present it to the larger dev team.

**Comment by RobPasMue** [comment]
https://github.com/ansys/actions/blob/815c6af616859c02f6f1f88130b5be09fb5cd78e/.github/workflows/ci_cd.yml#L24-L42

**Comment by RobPasMue** [comment]
Yep I'd keep it separated.

**Comment by MaxJPRey** [comment]
Let's keep it independent then.
