### ISSUE TITLE
Documentation style action fails when the diff is too large

### ISSUE THREAD

**Issue by greschd** [ansys/actions#655]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues

### 🐞 Description of the bug

The `doc-style` action fails if the diff of the PR is too large. This occurred for us on a large PR to the release branch: https://github.com/ansys/pyacp/actions/runs/12117576972/job/33780301776?pr=729#step:2:300

![Image](https://github.com/user-attachments/assets/c4082915-1cad-4376-a89f-cb2036180f2f)

**Comment by jorgepiloto** [comment]
This should be fixed in the current `main` branch, @greschd. Mind you giving it a try?

**Comment by RobPasMue** [comment]
Related to #441

**Comment by RobPasMue** [comment]
Related to #545

**Comment by greschd** [comment]
Indeed, it's fixed. Failing run: https://github.com/ansys/pyacp/actions/runs/12139544683/job/33847403221, and fixed when switching to `main`: https://github.com/ansys/pyacp/actions/runs/12139562014/job/33847473068

**Comment by RobPasMue** [comment]
8.2 (or even 9) should be released soon - containing this change :)
